name: Scheduled Greeting Job


on:
    schedule:
        - cron: '0 1,9,15,19 * * *'

    push:
        branches: [build]

    workflow_dispatch:

jobs:
    update-greeting-readme:
        runs-on: ubuntu-latest

        timeout-minutes: 2

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: build
            
            - name: Check for main.py
              id: check_file
              run: |
                if [ ! -f main.py ]; then
                    echo "main.py not found"
                    echo "::set-output name=found::false"
                else
                    echo "::set-output name=found::true"
                fi

            - name: Set up Python
              if: steps.check_file.outputs.found == 'true'
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
            
            - name: Install dependencies
              if: steps.check_file.outputs.found == 'true'
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt;
                fi

            - name: Run main.py
              if: steps.check_file.outputs.found == 'true'
              run: python main.py

            # - name: Configut

            - name: Copy README.md to main
              run: |
                git checkout main
                git checkout build -- README.md
                git add .
                git commit -m "Обновление README.md"
                git push origin main