name: Scheduled Greeting Job


on:
    schedule:
        - cron: '0 1,9,15,19 * * *'

    push:
        branches: [build]

    workflow_dispatch:

jobs:
    update-greeting-readme:
        permissions: 
            contents: write

        runs-on: ubuntu-latest

        timeout-minutes: 2

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: build
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then
                    pip install -r requirements.txt;
                fi

            - name: Check for main.py
              run: |
                if [ ! -f main.py ]; then
                    echo "main.py not found"
                    echo "FOUND=false" >> $GITHUB_ENV
                else
                    echo "FOUND=true" >> $GITHUB_ENV
                fi

            - name: Run main.py
              if: env.FOUND == 'true'
              run: |
                python main.py
                cat README.md

            - name: Configure git 
              run: |
                git config --global user.name "${{ github.actor }}"
                git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

            - name: Check for changes in README.md
              run: |
                git fetch origin main
                cat README.md
                git diff --quiet README.md
                echo $?
                if [ $? -ne 0 ] then
                    echo "README_HAS_CHANGES=1" >> $GITHUB_ENV
                else
                    echo "README_HAS_CHANGES=0" >> $GITHUB_ENV
                fi
                echo "README_HAS_CHANGES=${{ env.README_HAS_CHANGES }}"

            - name: Copy README.md to main
              if: env.README_HAS_CHANGES == '1'
              run: |
                git add .
                git commit -m "Обновление README.md"
                git checkout main
                git checkout build -- README.md

            - name: Commit and push changes
              if: env.README_HAS_CHANGES == '1'
              run: |
                git add .
                git commit -m "Обновление README.md" 
                git push origin main